apiVersion: v1
kind: Service
metadata:
  name: techlogix-inventory-service
spec:
  type: NodePort
  selector:
    app: techlogix-inventory
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080